# Generated by Django 4.1.7 on 2023-06-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='body',
        ),
    ]
